[tool.pyright]
ignore = [
    "**/typings",
]
exclude = [
    "**/.*",
    "__*",
    "**/node_modules",
    "**/typings",
    "venv",
]

typeCheckingMode = "basic"
stubPath = "typings"
typeshedPath = "typings"
pythonPlatform = "Linux"
venv = "venv"

reportMissingModuleSource = "none"
reportUnnecessaryTypeIgnoreComment = "error"
