name: Format justfiles
"on":
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/format-just.yaml
      - flake.lock
      - '**/.justfile'
      - '**/justfile'
      - '**/*.just'

jobs:
  format-just:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Format justfile
        run: nix develop --command just --check --fmt --unstable
