name: MicroPython

"on":
  pull_request:
    branches: ["main"]
    paths:
      - '**.nix'
      - .github/workflows/micropython.yaml
      - flake.lock
  push:
    branches: ["main"]
    paths:
      - '**.nix'
      - .github/workflows/micropython.yaml
      - flake.lock
  workflow_dispatch:

jobs:
  micropython:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - name: Build
        run: nix build .#micropython
      - name: Upload MicroPython
        uses: actions/upload-artifact@v4
        with:
          name: micropython
          path: |
            result/bin/RPI_PICO.uf2
