name: Pre-commit auto-update

"on":
  schedule:
    # Once a month on the 2nd
    - cron: "0 0 2 * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-commit-autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update pre-commit hooks
        run: pre-commit autoupdate
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          assignees: ${{ github.repository_owner }}
          branch: "update/pre-commit-hooks"
          commit-message: "chore(deps): Update pre-commit hooks"
          title: "chore(deps): Update pre-commit hooks"
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
