name: Ruff
"on":
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/ruff.yaml
      - flake.lock
      - pyproject.toml
      - requirements-dev.txt
      - '**.py'

permissions:
  checks: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Cache Python virtual environment
        uses: actions/cache@v4
        with:
          key: venv-${{ runner.os }}-${{ hashFiles('flake.lock') }}-${{ hashFiles('requirements-dev.txt') }}
          path: .venv
      - name: Format with Ruff
        run: nix develop --command ruff format
      - name: Fix Ruff checks
        run: nix develop --command ruff check --fix
      - uses: reviewdog/action-suggester@v1
        with:
          fail_on_error: true
          github_token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          tool_name: ruff
