name: Ruff
"on":
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/ruff.yaml
      - pyproject.toml
      - '**.py'

permissions:
  checks: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: chartboost/ruff-action@v1
        with:
          args: format
      - uses: chartboost/ruff-action@v1
        with:
          args: check --fix
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: ruff
