name: Test update-nix-direnv.nu
"on":
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/test-update-nix-direnv.yaml
      - flake.lock
      - update-nix-direnv.nu
      - update-nix-direnv-tests.nu
  push:
    branches: ["main"]
    paths:
      - .github/workflows/test-update-nix-direnv.yaml
      - flake.lock
      - update-nix-direnv.nu
      - update-nix-direnv-tests.nu
  workflow_dispatch:

jobs:
  test-update-nix-direnv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Run the Nushell tests
        run: nix develop --command nu update-nix-direnv-tests.nu
